### ISSUE TITLE
Hello i just want to say hi

### ISSUE THREAD

**Issue by Toolsclub** [chimurai/requirements#383]
hey stephen i know this is not a support channel, but i just want to ask a quick question 😢

Regarding of your Http-proxy-middleware lib, is there a way to use proxy before that

i mean, when i call

const proxyMiddleware = createProxyMiddleware({
  target: 'http://api.ipify.org?format=json',
  changeOrigin: true,
});
app.use('/checkip', proxyMiddleware);

it returns my IP, the IP of the server, i want to use a proxy so when that code is called, it'll show the proxy's ip instead

is there a way to do so

thanks 
![image](https://github.com/chimurai/requirements/assets/155623172/44c7249a-80bd-490e-a090-f728be5decf3)

**Comment by chimurai** [comment]
Wrong repo.

You can post your questions here: https://github.com/chimurai/http-proxy-middleware/discussions
